doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            ###Основные модули Core начало###
            #Модуль языки Languages
            LanguagesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Core/Languages/Entity'
                prefix: 'Module\Core\Languages\Entity'
                alias: LanguagesModule
            #Модуль категории Categories
            CategoriesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Core/Categories/Entity'
                prefix: 'Module\Core\Categories\Entity'
                alias: CategoriesModule
            #Модуль страны Countries
            CountriesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Core/Countries/Entity'
                prefix: 'Module\Core\Countries\Entity'
                alias: CountriesModule
            ###Основные модули Core конец###


            ###Вспомогательные модули Shared начало###
            #Модуль Роли Персоны
            RoleStatusModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Shared/RoleStatus/Entity'
                prefix: 'Module\Shared\RoleStatus\Entity'
                alias: RoleStatusModule
            #Модуль Индустрия Industries
            IndustriesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Shared/Industries/Entity'
                prefix: 'Module\Shared\Industries\Entity'
                alias: IndustriesModule
            #Модуль Индустрия Industries
            MissionsStatementsModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Shared/MissionsStatements/Entity'
                prefix: 'Module\Shared\MissionsStatements\Entity'
                alias: MissionsStatementsModule
            ###Вспомогательные модули Shared конец###


            ###Модули Employees начало###
            #Главный модуль Employees
            EmployeesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Employees/Employees/Entity'
                prefix: 'Module\Employees\Employees\Entity'
                alias: EmployeesModule
            #Модуль EmployeesJobTitle
            EmployeesModule_JobTitle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Employees/EmployeesJobTitle/Entity'
                prefix: 'Module\Employees\EmployeesJobTitle\Entity'
                alias: EmployeesModule_JobTitle
            ###Модули Employees конец###


            ###Модули PERSONS начало###
            #Модуль MaritalStatus
            PersonsModule_MaritalStatus:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Persons/MaritalStatus/Entity'
                prefix: 'Module\Persons\MaritalStatus\Entity'
                alias: PersonsModule_MaritalStatus
            #Модуль MaritalStatus
            PersonsModule_EducationLevels:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Persons/EducationLevels/Entity'
                prefix: 'Module\Persons\EducationLevels\Entity'
                alias: PersonsModule_EducationLevels
            ###Модули PERSONS конец###

#        controller_resolver:
#            auto_mapping: false

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
