doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            LanguageModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Languages/Entity'
                prefix: 'Module\Languages\Entity'
                alias: LanguagesModule
            CategoriesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Categories/Entity'
                prefix: 'Module\Categories\Entity'
                alias: CategoriesModule
            CountriesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Countries/Entity'
                prefix: 'Module\Countries\Entity'
                alias: CountriesModule


            ###Модули Employees начало###
            #Главный модуль Employees
            EmployeesModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Employees/Employees/Entity'
                prefix: 'Module\Employees\Employees\Entity'
                alias: EmployeesModule
            #Модуль EmployeesJobTitle
            EmployeesModule_JobTitle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Employees/EmployeesJobTitle/Entity'
                prefix: 'Module\Employees\EmployeesJobTitle\Entity'
                alias: EmployeesModule_JobTitle
            ###Модули Employees конец###


            ###Модули PERSONS начало###
            #Модуль MaritalStatus
            PersonsModule_MaritalStatus:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/module/Persons/MaritalStatus/Entity'
                prefix: 'Module\Persons\MaritalStatus\Entity'
                alias: PersonsModule_MaritalStatus
            ###Модули PERSONS конец###

#        controller_resolver:
#            auto_mapping: false

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
