<?php

namespace ContainerFCuexxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeesControllerService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the public 'Module\Employees\Controller\Api\EmployeesController' shared autowired service.
     *
     * @return \Module\Employees\Controller\Api\EmployeesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Employees'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'EmployeesController.php';

        return $container->services['Module\\Employees\\Controller\\Api\\EmployeesController'] = new \Module\Employees\Controller\Api\EmployeesController(($container->privates['Module\\Employees\\Service\\EmployeesService'] ?? $container->load('getEmployeesServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
