<?php

namespace ContainerFCuexxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeesServiceService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the private 'Module\Employees\Service\EmployeesService' shared autowired service.
     *
     * @return \Module\Employees\Service\EmployeesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Employees'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmployeesService.php';

        return $container->privates['Module\\Employees\\Service\\EmployeesService'] = new \Module\Employees\Service\EmployeesService(($container->privates['Module\\Employees\\Repository\\EmployeesRepository'] ?? $container->load('getEmployeesRepositoryService')), ($container->privates['Module\\Languages\\Repository\\LanguagesRepository'] ?? $container->load('getLanguagesRepositoryService')), ($container->privates['Module\\Common\\Service\\LanguagesValidationService'] ?? $container->load('getLanguagesValidationServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
