<?php

namespace ContainerFCuexxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesControllerService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the public 'Module\Languages\Controller\Api\LanguagesController' shared autowired service.
     *
     * @return \Module\Languages\Controller\Api\LanguagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'LanguagesController.php';

        return $container->services['Module\\Languages\\Controller\\Api\\LanguagesController'] = new \Module\Languages\Controller\Api\LanguagesController(($container->privates['Module\\Languages\\Service\\LanguagesService'] ?? $container->load('getLanguagesServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
