<?php

namespace ContainerFCuexxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesValidationServiceService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the private 'Module\Common\Service\LanguagesValidationService' shared autowired service.
     *
     * @return \Module\Common\Service\LanguagesValidationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Common'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LanguagesValidationService.php';

        return $container->privates['Module\\Common\\Service\\LanguagesValidationService'] = new \Module\Common\Service\LanguagesValidationService(($container->privates['Module\\Languages\\Repository\\LanguagesRepository'] ?? $container->load('getLanguagesRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
