<?php

namespace Container9xDnQwX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeesControllerService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the public 'Module\Employees\Controller\Api\EmployeesController' shared autowired service.
     *
     * @return \Module\Employees\Controller\Api\EmployeesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Employees'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'EmployeesController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Employees'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmployeesService.php';

        $a = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        return $container->services['Module\\Employees\\Controller\\Api\\EmployeesController'] = new \Module\Employees\Controller\Api\EmployeesController(new \Module\Employees\Service\EmployeesService(($container->privates['Module\\Employees\\Repository\\EmployeesRepository'] ?? $container->load('getEmployeesRepositoryService')), ($container->privates['Module\\Languages\\Repository\\LanguagesRepository'] ?? $container->load('getLanguagesRepositoryService')), ($container->privates['Module\\Common\\Service\\LanguagesValidationService'] ?? $container->load('getLanguagesValidationServiceService')), $a), $a, ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
