<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountriesControllerService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the public 'Module\Core\Countries\Controller\Api\CountriesController' shared autowired service.
     *
     * @return \Module\Core\Countries\Controller\Api\CountriesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Countries'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'CountriesController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Countries'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CountriesService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Countries'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CountriesValidationService.php';

        $a = ($container->privates['Module\\Core\\Countries\\Repository\\CountriesRepository'] ?? $container->load('getCountriesRepositoryService'));
        $b = ($container->privates['Module\\Core\\Countries\\Repository\\CountryTranslationsRepository'] ?? $container->load('getCountryTranslationsRepositoryService'));
        $c = ($container->privates['Module\\Common\\Proxy\\Core\\LanguagesProxyService'] ?? $container->load('getLanguagesProxyServiceService'));
        $d = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        return $container->services['Module\\Core\\Countries\\Controller\\Api\\CountriesController'] = new \Module\Core\Countries\Controller\Api\CountriesController(new \Module\Core\Countries\Service\CountriesService($a, $b, $c, new \Module\Core\Countries\Service\CountriesValidationService($a, $b, $c, $d), ($container->privates['Module\\Common\\Service\\ImageService'] ?? $container->load('getImageServiceService')), ($container->privates['Module\\Common\\Helpers\\FieldUpdateHelper'] ?? $container->load('getFieldUpdateHelperService')), $d), $d, ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
