<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldUpdateHelperService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the private 'Module\Common\Helpers\FieldUpdateHelper' shared autowired service.
     *
     * @return \Module\Common\Helpers\FieldUpdateHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Common'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FieldUpdateHelper.php';

        return $container->privates['Module\\Common\\Helpers\\FieldUpdateHelper'] = new \Module\Common\Helpers\FieldUpdateHelper(($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
