<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndustriesControllerService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the public 'Module\Shared\Industries\Controller\Api\IndustriesController' shared autowired service.
     *
     * @return \Module\Shared\Industries\Controller\Api\IndustriesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Industries'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'IndustriesController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Industries'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'IndustriesService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Industries'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'IndustriesValidationService.php';

        $a = ($container->privates['Module\\Shared\\Industries\\Repository\\IndustriesRepository'] ?? $container->load('getIndustriesRepositoryService'));
        $b = ($container->privates['Module\\Shared\\Industries\\Repository\\IndustryTranslationsRepository'] ?? $container->load('getIndustryTranslationsRepositoryService'));
        $c = ($container->privates['Module\\Common\\Proxy\\Core\\LanguagesProxyService'] ?? $container->load('getLanguagesProxyServiceService'));
        $d = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        return $container->services['Module\\Shared\\Industries\\Controller\\Api\\IndustriesController'] = new \Module\Shared\Industries\Controller\Api\IndustriesController(new \Module\Shared\Industries\Service\IndustriesService($a, $b, $c, new \Module\Shared\Industries\Service\IndustriesValidationService($a, $b, $c, $d), ($container->privates['Module\\Common\\Service\\ImageService'] ?? $container->load('getImageServiceService')), ($container->privates['Module\\Common\\Helpers\\FieldUpdateHelper'] ?? $container->load('getFieldUpdateHelperService')), $d), $d, ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
