<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesValidationServiceService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the private 'Module\Core\Languages\Service\LanguagesValidationService' shared autowired service.
     *
     * @return \Module\Core\Languages\Service\LanguagesValidationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LanguagesValidationService.php';

        return $container->privates['Module\\Core\\Languages\\Service\\LanguagesValidationService'] = new \Module\Core\Languages\Service\LanguagesValidationService(($container->privates['Module\\Core\\Languages\\Repository\\LanguagesRepository'] ?? $container->load('getLanguagesRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
