<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesProxyServiceService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the private 'Module\Common\Proxy\Core\LanguagesProxyService' shared autowired service.
     *
     * @return \Module\Common\Proxy\Core\LanguagesProxyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Common'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'LanguagesProxyService.php';

        return $container->privates['Module\\Common\\Proxy\\Core\\LanguagesProxyService'] = new \Module\Common\Proxy\Core\LanguagesProxyService(($container->privates['Module\\Core\\Languages\\Repository\\LanguagesRepository'] ?? $container->load('getLanguagesRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Module\\Core\\Languages\\Service\\LanguagesValidationService'] ?? $container->load('getLanguagesValidationServiceService')));
    }
}
