<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaritalStatusControllerService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the public 'Module\Persons\MaritalStatus\Controller\Api\MaritalStatusController' shared autowired service.
     *
     * @return \Module\Persons\MaritalStatus\Controller\Api\MaritalStatusController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Persons'.\DIRECTORY_SEPARATOR.'MaritalStatus'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'MaritalStatusController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Persons'.\DIRECTORY_SEPARATOR.'MaritalStatus'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MaritalStatusService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Persons'.\DIRECTORY_SEPARATOR.'MaritalStatus'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MaritalStatusValidationService.php';

        $a = ($container->privates['Module\\Persons\\MaritalStatus\\Repository\\MaritalStatusRepository'] ?? $container->load('getMaritalStatusRepositoryService'));
        $b = ($container->privates['Module\\Persons\\MaritalStatus\\Repository\\MaritalStatusTranslationsRepository'] ?? $container->load('getMaritalStatusTranslationsRepositoryService'));
        $c = ($container->privates['Module\\Common\\Proxy\\Core\\LanguagesProxyService'] ?? $container->load('getLanguagesProxyServiceService'));
        $d = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        return $container->services['Module\\Persons\\MaritalStatus\\Controller\\Api\\MaritalStatusController'] = new \Module\Persons\MaritalStatus\Controller\Api\MaritalStatusController(new \Module\Persons\MaritalStatus\Service\MaritalStatusService($a, $b, $c, new \Module\Persons\MaritalStatus\Service\MaritalStatusValidationService($a, $b, $c, $d), ($container->privates['Module\\Common\\Service\\ImageService'] ?? $container->load('getImageServiceService')), ($container->privates['Module\\Common\\Helpers\\FieldUpdateHelper'] ?? $container->load('getFieldUpdateHelperService')), $d), $d, ($container->privates['Module\\Common\\Factory\\ResponseFactory'] ?? $container->load('getResponseFactoryService')));
    }
}
