<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_DoctrineHelperService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.doctrine_helper' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'maker-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Doctrine'.\DIRECTORY_SEPARATOR.'DoctrineHelper.php';

        $a = ($container->privates['doctrine.orm.default_attribute_metadata_driver'] ?? $container->load('getDoctrine_Orm_DefaultAttributeMetadataDriverService'));

        return $container->privates['maker.doctrine_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper('Module\\Entity', ($container->services['doctrine'] ?? $container->load('getDoctrineService')), ['default' => [['Module\\Core\\Languages\\Entity', $a], ['Module\\Core\\Categories\\Entity', $a], ['Module\\Core\\Countries\\Entity', $a], ['Module\\Shared\\RoleStatus\\Entity', $a], ['Module\\Shared\\Industries\\Entity', $a], ['Module\\Employees\\Employees\\Entity', $a], ['Module\\Employees\\EmployeesJobTitle\\Entity', $a], ['Module\\Persons\\MaritalStatus\\Entity', $a], ['Module\\Persons\\EducationLevels\\Entity', $a]]]);
    }
}
