<?php

namespace ContainerKWUSDw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseFactoryService extends Module_KernelDevDebugContainer
{
    /**
     * Gets the private 'Module\Common\Factory\ResponseFactory' shared autowired service.
     *
     * @return \Module\Common\Factory\ResponseFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Common'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ResponseFactory.php';

        return $container->privates['Module\\Common\\Factory\\ResponseFactory'] = new \Module\Common\Factory\ResponseFactory(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
