#controllers:
 #   resource:
  #      path: ../src/Controller/
   #     namespace: App\Controller
    #type: attribute

#модули
module_controllers:
    resource: '../module/*/Controller/Api/'
    type: attribute

# Рекурсивная настройка для подмодулей
nested_module_controllers:
    resource: '../module/*/*/Controller/Api/'
    type: attribute
    #  name_prefix: 'api_nested_'   # Префикс для маршрутов подмодулей

language_controller:
    resource: '../module/Languages/Controller/Api/'
    type: attribute

categories_controller:
    resource: '../module/Categories/Controller/Api/'
    type: attribute

countries_controller:
    resource: '../module/Countries/Controller/Api/'
    type: attribute


###Модули Employees начало###
#Главный модуль Employees
employee_controller:
    resource: '../module/Employees/Employees/Controller/Api/'
    type: attribute
#Модуль EmployeesJobTitle
employee_job_title_controller:
    resource: '../module/Employees/EmployeesJobTitle/Controller/Api/'
    type: attribute
###Модули Employees конец###


###Модули PERSONS начало###
#Модуль MaritalStatus
marital_status_controller:
    resource: '../module/Persons/MaritalStatus/Controller/Api/'
    type: attribute
###Модули PERSONS конец###