#controllers:
 #   resource:
  #      path: ../src/Controller/
   #     namespace: App\Controller
    #type: attribute

#модули
module_controllers:
    resource: '../module/*/Controller/Api/'
    type: attribute

# Рекурсивная настройка для подмодулей
nested_module_controllers:
    resource: '../module/*/*/Controller/Api/'
    type: attribute
    #  name_prefix: 'api_nested_'   # Префикс для маршрутов подмодулей

###Основные модули Core начало###
#Модуль языки Languages
language_controller:
    resource: '../module/Core/Languages/Controller/Api/'
    type: attribute
#Модуль категории Categories
categories_controller:
    resource: '../module/Core/Categories/Controller/Api/'
    type: attribute
#Модуль страны Countries
countries_controller:
    resource: '../module/Core/Countries/Controller/Api/'
    type: attribute
###Основные модули Core конец###


###Вспомогательные модули Shared начало###
#Модуль Индустрия Industries
industries_controller:
    resource: '../module/Shared/Industries/Controller/Api/'
    type: attribute
#Модуль Роли Персоны
roles_status_controller:
    resource: '../module/Shared/RoleStatus/Controller/Api/'
    type: attribute
###Вспомогательные модули Shared конец###


###Модули Employees начало###
#Главный модуль Employees
employee_controller:
    resource: '../module/Employees/Employees/Controller/Api/'
    type: attribute
#Модуль EmployeesJobTitle
employee_job_title_controller:
    resource: '../module/Employees/EmployeesJobTitle/Controller/Api/'
    type: attribute
###Модули Employees конец###


###Модули PERSONS начало###
#Модуль MaritalStatus
marital_status_controller:
    resource: '../module/Persons/MaritalStatus/Controller/Api/'
    type: attribute
#Модуль EducationLevels
education_levels_controller:
    resource: '../module/Persons/EducationLevels/Controller/Api/'
    type: attribute
###Модули PERSONS конец###