#controllers:
 #   resource:
  #      path: ../src/Controller/
   #     namespace: App\Controller
    #type: attribute

module_controllers:
    resource: '../module/*/Controller/Api/'
    type: attribute

language_controller:
    resource: '../module/Languages/Controller/Api/'
    type: attribute

employee_controller:
    resource: '../module/Employees/Controller/Api/'
    type: attribute

categories_controller:
    resource: '../module/Categories/Controller/Api/'
    type: attribute

countries_controller:
    resource: '../module/Countries/Controller/Api/'
    type: attribute