parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Symfony\Component\Validator\Validator\ValidatorInterface:
        alias: validator

    Module\Common\Proxy\Core\LanguagesProxyService:
        alias: languagesProxy

    Module\Common\Proxy\Core\CategoriesProxyService:
        alias: categoriesProxy

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Module\:
        resource: '../module/*'
        exclude:
            - '../module/Kernel.php'

    # Добавляем ValidationService как общий сервис
    #Module\Common\Service\LanguagesValidationService:
    #    arguments:
    #        $languagesRepository: '@Module\Languages\Repository\LanguagesRepository'
    #        $logger: '@logger'

    ###Основные модули Core начало###
    #Модуль языки Languages
    Module\Core\Languages\Controller\Api\LanguagesController:
        tags: ['controller.service_arguments']
        public: true
    #Модуль категории Categories
    Module\Core\Categories\Controller\Api\CategoriesController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модуль страны Countries
    Module\Core\Countries\Controller\Api\CountriesController:
        tags: [ 'controller.service_arguments' ]
        public: true
    ###Основные модули Core конец###


    ###Вспомогательные модули Shared начало###
    #Модуль Роли Персоны
    Module\Shared\RoleStatus\Controller\Api\RoleStatusController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модуль Индустрия Industries
    Module\Shared\Industries\Controller\Api\IndustriesController:
        tags: [ 'controller.service_arguments' ]
        public: true
    ###Вспомогательные модули Shared конец###


    ###Модули Employees начало###
    #Главный модуль Employees
    Module\Employees\Employees\Controller\Api\EmployeesController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модуль EmployeesJobTitle
    Module\Employees\EmployeesJobTitle\Controller\Api\EmployeesJobTitleController:
        tags: [ 'controller.service_arguments' ]
        public: true
    ###Модули Employees конец###


    ###Модули PERSONS начало###
    #Модуль MaritalStatus
    Module\Persons\MaritalStatus\Controller\Api\MaritalStatusController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модуль EducationLevels
    Module\Persons\EducationLevels\Controller\Api\EducationLevelsController:
        tags: [ 'controller.service_arguments' ]
        public: true
    ###Модули PERSONS конец###