parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Symfony\Component\Validator\Validator\ValidatorInterface:
        alias: validator

    Module\Common\Service\LanguagesProxyService:
        alias: languagesProxy

    Module\Common\Service\CategoriesProxyService:
        alias: categoriesProxy

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Module\:
        resource: '../module/*'
        exclude:
            - '../module/Kernel.php'

    # Добавляем ValidationService как общий сервис
    #Module\Common\Service\LanguagesValidationService:
    #    arguments:
    #        $languagesRepository: '@Module\Languages\Repository\LanguagesRepository'
    #        $logger: '@logger'

    Module\Languages\Controller\Api\LanguagesController:
        tags: ['controller.service_arguments']
        public: true

    Module\Categories\Controller\Api\CategoriesController:
        tags: [ 'controller.service_arguments' ]
        public: true
        #condition: '%modules_config.modules.categories.enabled%'

    Module\Countries\Controller\Api\CountriesController:
        tags: [ 'controller.service_arguments' ]
        public: true
        #condition: '%modules_config.modules.countries.enabled%'


    ###Модули Employees начало###
    #Главный модуль Employees
    Module\Employees\Employees\Controller\Api\EmployeesController:
        tags: [ 'controller.service_arguments' ]
        public: true
        #condition: '%modules_config.modules.employees.enabled%'
    #Модуль EmployeesJobTitle
    Module\Employees\EmployeesJobTitle\Controller\Api\EmployeesJobTitleController:
        tags: [ 'controller.service_arguments' ]
        public: true
        #condition: '%modules_config.modules.employees.submodules.employeesJobTitle.enabled%'
    ###Модули Employees конец###


    ###Модули PERSONS начало###
    #Модуль MaritalStatus
    Module\Persons\MaritalStatus\Controller\Api\MaritalStatusController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модуль EducationLevels
    Module\Persons\EducationLevels\Controller\Api\EducationLevelsController:
        tags: [ 'controller.service_arguments' ]
        public: true
    ###Модули PERSONS конец###