parameters:
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Symfony\Component\Validator\Validator\ValidatorInterface:
        alias: validator

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Module\:
        resource: '../module/*'
        exclude:
            - '../module/Kernel.php'



    # Добавляем ValidationService как общий сервис
    #Module\Common\Service\LanguagesValidationService:
    #    arguments:
    #        $languagesRepository: '@Module\Languages\Repository\LanguagesRepository'
    #        $logger: '@logger'

    Module\Languages\Controller\Api\LanguagesController:
        tags: ['controller.service_arguments']
        public: true

    #Модули сотрудника начало
    Module\Employees\Controller\Api\EmployeesController:
        tags: [ 'controller.service_arguments' ]
        public: true
    Module\Employees\EmployeesJobTitle\Controller\Api\EmployeesJobTitleController:
        tags: [ 'controller.service_arguments' ]
        public: true
    #Модули сотрудника конец

    Module\Categories\Controller\Api\CategoriesController:
        tags: [ 'controller.service_arguments' ]
        public: true

    Module\Countries\Controller\Api\CountriesController:
        tags: [ 'controller.service_arguments' ]
        public: true