<?php

namespace ContainerCI7iQwS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeServiceService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the private 'Module\Employees\Service\EmployeeService' shared autowired service.
     *
     * @return \Module\Employees\Service\EmployeeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Employees'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmployeeService.php';

        return $container->privates['Module\\Employees\\Service\\EmployeeService'] = new \Module\Employees\Service\EmployeeService(($container->privates['Module\\Employees\\Repository\\EmployeeRepository'] ?? $container->load('getEmployeeRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
