<?php

namespace ContainerCI7iQwS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageControllerService extends Module_KernelTestDebugContainer
{
    /**
     * Gets the public 'Module\Languages\Controller\Api\LanguageController' shared autowired service.
     *
     * @return \Module\Languages\Controller\Api\LanguageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'module'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'LanguageController.php';

        return $container->services['Module\\Languages\\Controller\\Api\\LanguageController'] = new \Module\Languages\Controller\Api\LanguageController(($container->privates['Module\\Languages\\Service\\LanguageService'] ?? $container->load('getLanguageServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
