<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFCuexxn\Module_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFCuexxn/Module_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFCuexxn.legacy');

    return;
}

if (!\class_exists(Module_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFCuexxn\Module_KernelTestDebugContainer::class, Module_KernelTestDebugContainer::class, false);
}

return new \ContainerFCuexxn\Module_KernelTestDebugContainer([
    'container.build_hash' => 'FCuexxn',
    'container.build_id' => '4b2a7fde',
    'container.build_time' => 1730304181,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFCuexxn');
