<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3wh20C\Module_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3wh20C/Module_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerG3wh20C.legacy');

    return;
}

if (!\class_exists(Module_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerG3wh20C\Module_KernelTestDebugContainer::class, Module_KernelTestDebugContainer::class, false);
}

return new \ContainerG3wh20C\Module_KernelTestDebugContainer([
    'container.build_hash' => 'G3wh20C',
    'container.build_id' => '5d3a1bff',
    'container.build_time' => 1730056838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3wh20C');
