<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVVzK7xx\Module_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVVzK7xx/Module_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVVzK7xx.legacy');

    return;
}

if (!\class_exists(Module_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVVzK7xx\Module_KernelDevDebugContainer::class, Module_KernelDevDebugContainer::class, false);
}

return new \ContainerVVzK7xx\Module_KernelDevDebugContainer([
    'container.build_hash' => 'VVzK7xx',
    'container.build_id' => 'd0f0a34b',
    'container.build_time' => 1730058665,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVVzK7xx');
