<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xDnQwX\Module_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xDnQwX/Module_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9xDnQwX.legacy');

    return;
}

if (!\class_exists(Module_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9xDnQwX\Module_KernelDevDebugContainer::class, Module_KernelDevDebugContainer::class, false);
}

return new \Container9xDnQwX\Module_KernelDevDebugContainer([
    'container.build_hash' => '9xDnQwX',
    'container.build_id' => '4758eaf3',
    'container.build_time' => 1730314043,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xDnQwX');
