<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_get_languages' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::getLanguages'], [], [['text', '/api/languages']], [], [], []],
    'api_get_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::getLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages']], [], [], []],
    'api_add_language' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::addLanguage'], [], [['text', '/api/languages/add']], [], [], []],
    'api_update_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::updateLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/update']], [], [], []],
    'api_delete_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::deleteLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/delete']], [], [], []],
    'api_get_employees' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::getEmployees'], [], [['text', '/api/employees']], [], [], []],
    'api_get_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::getEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees']], [], [], []],
    'api_add_employee' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::addEmployee'], [], [['text', '/api/employees/add']], [], [], []],
    'api_update_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::updateEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update']], [], [], []],
    'api_update_employee_field' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::updateEmployeeField'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update-field']], [], [], []],
    'api_delete_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::deleteEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/delete']], [], [], []],
    'Module\Languages\Controller\Api\LanguagesController::getLanguages' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::getLanguages'], [], [['text', '/api/languages']], [], [], []],
    'Module\Languages\Controller\Api\LanguagesController::getLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::getLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages']], [], [], []],
    'Module\Languages\Controller\Api\LanguagesController::addLanguage' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::addLanguage'], [], [['text', '/api/languages/add']], [], [], []],
    'Module\Languages\Controller\Api\LanguagesController::updateLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::updateLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/update']], [], [], []],
    'Module\Languages\Controller\Api\LanguagesController::deleteLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguagesController::deleteLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/delete']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::getEmployees' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::getEmployees'], [], [['text', '/api/employees']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::getEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::getEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::addEmployee' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::addEmployee'], [], [['text', '/api/employees/add']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::updateEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::updateEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::updateEmployeeField' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::updateEmployeeField'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update-field']], [], [], []],
    'Module\Employees\Controller\Api\EmployeesController::deleteEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeesController::deleteEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/delete']], [], [], []],
];
