<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_get_languages' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::getLanguages'], [], [['text', '/api/languages']], [], [], []],
    'api_get_id_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::getLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages']], [], [], []],
    'api_add_language' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::addLanguage'], [], [['text', '/api/languages/add']], [], [], []],
    'api_delete_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::deleteLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/delete']], [], [], []],
    'api_update_language' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::updateLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/update']], [], [], []],
    'api_get_employees' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::getEmployees'], [], [['text', '/api/employees']], [], [], []],
    'api_get_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::getEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees']], [], [], []],
    'api_add_employee' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::addEmployee'], [], [['text', '/api/employees/add']], [], [], []],
    'api_update_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::updateEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update']], [], [], []],
    'api_update_employee_field' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::updateEmployeeField'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update-field']], [], [], []],
    'api_delete_employee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::deleteEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/delete']], [], [], []],
    'Module\Languages\Controller\Api\LanguageController::getLanguages' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::getLanguages'], [], [['text', '/api/languages']], [], [], []],
    'Module\Languages\Controller\Api\LanguageController::getLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::getLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages']], [], [], []],
    'Module\Languages\Controller\Api\LanguageController::addLanguage' => [[], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::addLanguage'], [], [['text', '/api/languages/add']], [], [], []],
    'Module\Languages\Controller\Api\LanguageController::deleteLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::deleteLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/delete']], [], [], []],
    'Module\Languages\Controller\Api\LanguageController::updateLanguage' => [['id'], ['_controller' => 'Module\\Languages\\Controller\\Api\\LanguageController::updateLanguage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/languages/update']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::getEmployees' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::getEmployees'], [], [['text', '/api/employees']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::getEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::getEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::addEmployee' => [[], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::addEmployee'], [], [['text', '/api/employees/add']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::updateEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::updateEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::updateEmployeeField' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::updateEmployeeField'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/update-field']], [], [], []],
    'Module\Employees\Controller\Api\EmployeeController::deleteEmployee' => [['id'], ['_controller' => 'Module\\Employees\\Controller\\Api\\EmployeeController::deleteEmployee'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/employees/delete']], [], [], []],
];
